apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shared
  name: core-module
  labels:
    app: core-module
spec:
  replicas: 1
  selector:
     matchLabels:
       app: core-module
  template:
    metadata:
      labels:
        app: core-module
    spec:
      containers:
       - name: core-module
         image: gitlab.dokuma.digital:5050/eccellenza/shared-modules/core-module:PROFILE
         imagePullPolicy: Always
         ports:
         - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: shared
  name: core-backend-svc
spec:
  selector:
    app: core-module
  ports:
  - port: 8080
