name: Build
run-name: Triggered by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build-application:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - name: Get changes
        uses: actions/checkout@v4
      - name: Set up java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up maven repository
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "zim-repo",
                "username": "${{ secrets.ARTIFACTORY_USERNAME }}",
                "password": "${{ secrets.ARTIFACTORY_PASSWORD }}"
            }]
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: build image
        run: |
          mvn -DskipTests spring-boot:build-image
          docker tag core-backend ${{ secrets.DOCKER_REGISTRY_SPACE }}:uat
          docker push ${{ secrets.DOCKER_REGISTRY_SPACE }}:uat

  deploy-application:
    name: deploy
    needs: build-application
    runs-on: ubuntu-24.04
    steps:
      - name: Get changes
        uses: actions/checkout@v4
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.3
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Delete existing deployment
        run: kubectl delete deployment core-module -n shared
      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          namespace: shared
          manifests: |
            kubernetes
          images: |
            ${{ secrets.DOCKER_REGISTRY_SPACE }}:uat
          imagepullsecrets: |
            gitlab-container-registry
          

